export enum BaseNodeType {
  Project = 'Project',
  ProjectMember = 'ProjectMember',
  User = 'User',
  Budget = 'Budget',
  BudgetRecord = 'BudgetRecord',
  Partnership = 'Partnership',
  Ceremony = 'Ceremony',
  LanguageEngagement = 'LanguageEngagement',
  InternshipEngagement = 'InternshipEngagement',
  Film = 'Film',
  FundingAccount = 'FundingAccount',
  Language = 'Language',
  EthnologueLanguage = 'EthnologueLanguage',
  LiteracyMaterial = 'LiteracyMaterial',
  Zone = 'Zone',
  Region = 'Region',
  Organization = 'Organization',
  Partner = 'Partner',
  Product = 'Product',
  Song = 'Song',
  Story = 'Story',
  Unavailability = 'Unavailability',
  Education = 'Education',
}
