export enum BaseNodeType {
  Project = 'Project',
  ProjectMember = 'ProjectMember',
  User = 'User',
  Budget = 'Budget',
  BudgetRecord = 'BudgetRecord',
  Partnership = 'Partnership',
  Ceremony = 'Ceremony',
  LanguageEngagement = 'LanguageEngagement',
  InternshipEngagement = 'InternshipEngagement',
  Film = 'Film',
  FundingAccount = 'FundingAccount',
  Language = 'Language',
  EthnologueLanguage = 'EthnologueLanguage',
}
