name: Node Setup & Yarn Install
description: 'Setup Node.js and install dependencies with Yarn'
runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: 24

    - name: Yarn cache
      uses: actions/cache@v4
      with:
        path: |
          .yarn/cache
          node_modules
        key: yarn-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
        restore-keys: yarn-cache-

    - name: Install dependencies
      shell: bash
      run: corepack enable && yarn install
      env:
        YARN_ENABLE_GLOBAL_CACHE: 'false' # Use local cache folder to keep downloaded archives
        YARN_NM_MODE: 'hardlinks-local' # Hardlinks-(local|global) reduces io / node_modules size
