root: true
plugins:
  - '@seedcompany'
  - typescript-sort-keys
  - no-only-tests
extends:
  - plugin:@seedcompany/nestjs
rules:
  no-console: error
  no-only-tests/no-only-tests: error
  '@typescript-eslint/naming-convention':
    - warn
    - selector: typeLike
      format: [PascalCase]
    - selector: interface
      format: [PascalCase]
      custom: # Forbid I prefixed type names
        regex: ^I[A-Z].+$
        match: false
    - selector: memberLike
      format: [camelCase]
      leadingUnderscore: forbid
      # allow `__typename` exception since it's a GQL standard.
      # `property` group selector is precedence is bugged
      # https://github.com/typescript-eslint/typescript-eslint/issues/2860
    - selector: [classProperty, objectLiteralProperty, typeProperty]
      filter: __typename
      format: ~
    - selector: [classProperty, objectLiteralProperty, typeProperty]
      format: [camelCase, PascalCase]
      leadingUnderscore: forbid
    - selector: enumMember
      format: [PascalCase, UPPER_CASE]
      leadingUnderscore: forbid
    - selector: parameter
      format: [camelCase]
      leadingUnderscore: allow
  no-restricted-imports:
    - error
    - paths:
        - name: '@nestjs/cqrs'
          message: Import from our core module instead
        - name: '@nestjs/common'
          importNames:
            - BadRequestException
            - HttpException
            - UnauthorizedException
            - MethodNotAllowedException
            - NotFoundException
            - ForbiddenException
            - NotAcceptableException
            - RequestTimeoutException
            - ConflictException
            - GoneException
            - PayloadTooLargeException
            - UnsupportedMediaTypeException
            - UnprocessableEntityException
            - InternalServerErrorException
            - NotImplementedException
            - HttpVersionNotSupportedException
            - BadGatewayException
            - ServiceUnavailableException
            - GatewayTimeoutException
          message: Use our exceptions in common folder instead

  # TODO Enable this and fix errors (both types & logic changes will be needed)
  '@typescript-eslint/no-unnecessary-condition': off
