nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.3.cjs

logFilters:
  # discard these messages that flood the build log
  - { code: YN0013, level: '${VERBOSE_YARN_LOG:-info}' } # fetching package
  - { code: YN0019, level: '${VERBOSE_YARN_LOG:-info}' } # unused cache entry
  # discard skipped build script message.
  # You think we'd know that since we went through the trouble explicitly disabling the package. smh.
  - { code: YN0005, level: discard }

packageExtensions:
  "@nestjs/graphql@*":
    peerDependencies:
      class-transformer: "*"
      class-validator: "*"
  "cypher-query-builder@*":
    peerDependencies:
      "@types/node": "*"
      rxjs: ^7
