logFilters:
  - code: YN0013
    level: "${VERBOSE_YARN_LOG:-info}"
  - code: YN0019
    level: "${VERBOSE_YARN_LOG:-info}"
  - code: YN0005
    level: discard

nodeLinker: node-modules

packageExtensions:
  cypher-query-builder@*:
    peerDependencies:
      "@types/node": "*"
      rxjs: ^7
