nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.0.2.cjs

logFilters:
  # discard these messages that flood the build log
  - { code: YN0013, level: discard } # fetching package
  - { code: YN0019, level: discard } # unused cache entry

packageExtensions:
  "@nestjs/graphql@*":
    peerDependencies:
      class-transformer: 0.4.0
      class-validator: 0.13.1
  "cypher-query-builder@*":
    peerDependencies:
      "@types/node": ^16
      rxjs: ^7
