nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.2.0.cjs

logFilters:
  # discard these messages that flood the build log
  - { code: YN0013, level: discard } # fetching package
  - { code: YN0019, level: discard } # unused cache entry

packageExtensions:
  "@aws-sdk/client-s3@*":
    dependencies:
      "@aws-sdk/signature-v4-crt": ^3
  "@aws-sdk/s3-request-presigner@*":
    dependencies:
      "@aws-sdk/signature-v4-crt": ^3
  "@nestjs/graphql@*":
    peerDependencies:
      class-transformer: "*"
      class-validator: "*"
  "cypher-query-builder@*":
    peerDependencies:
      "@types/node": "*"
      rxjs: ^7
