nodeLinker: node-modules

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-2.4.0.cjs

logFilters:
  # discard these messages that flood the build log
  - { code: YN0013, level: discard } # fetching package
  - { code: YN0019, level: discard } # unused cache entry
