/* eslint typescript-sort-keys/string-enum: "warn" */

import { registerEnumType } from '@nestjs/graphql';

export enum Powers {
  BetaFeatures = 'BetaFeatures',
  CreateBudget = 'CreateBudget',
  CreateBudgetRecord = 'CreateBudgetRecord',
  CreateCeremony = 'CreateCeremony',
  CreateChangeRequest = 'CreateChangeRequest',
  CreateDirectory = 'CreateDirectory',
  CreateEducation = 'CreateEducation',
  CreateEthnoArt = 'CreateEthnoArt',
  CreateEthnologueLanguage = 'CreateEthnologueLanguage',
  CreateFieldRegion = 'CreateFieldRegion',
  CreateFieldZone = 'CreateFieldZone',
  CreateFile = 'CreateFile',
  CreateFileVersion = 'CreateFileVersion',
  CreateFilm = 'CreateFilm',
  CreateFundingAccount = 'CreateFundingAccount',
  CreateInternshipEngagement = 'CreateInternshipEngagement',
  CreateLanguage = 'CreateLanguage',
  CreateLanguageEngagement = 'CreateLanguageEngagement',
  CreateLiteracyMaterial = 'CreateLiteracyMaterial',
  CreateLocation = 'CreateLocation',
  CreateOrganization = 'CreateOrganization',
  CreatePartner = 'CreatePartner',
  CreatePartnership = 'CreatePartnership',
  CreatePost = 'CreatePost',
  CreateProduct = 'CreateProduct',
  CreateProject = 'CreateProject',
  CreateProjectEngagement = 'CreateProjectEngagement',
  // place holder if needed
  CreateProjectMember = 'CreateProjectMember',
  CreateRegion = 'CreateRegion',
  CreateSong = 'CreateSong',
  CreateStory = 'CreateStory',
  CreateTranslationEngagement = 'CreateTranslationEngagement',
  CreateUnavailability = 'CreateUnavailability',
  CreateUser = 'CreateUser',
  CreateZone = 'CreateZone',

  DeleteBudget = 'DeleteBudget',
  DeleteBudgetRecord = 'DeleteBudgetRecord',
  DeleteCeremony = 'DeleteCeremony',
  DeleteDirectory = 'DeleteDirectory',
  DeleteEducation = 'DeleteEducation',
  DeleteEthnoArt = 'DeleteEthnoArt',
  DeleteEthnologueLanguage = 'DeleteEthnologueLanguage',
  DeleteFieldRegion = 'DeleteFieldRegion',
  DeleteFieldZone = 'DeleteFieldZone',
  DeleteFile = 'DeleteFile',
  DeleteFileVersion = 'DeleteFileVersion',
  DeleteFilm = 'DeleteFilm',
  DeleteFundingAccount = 'DeleteFundingAccount',
  DeleteInternshipEngagement = 'DeleteInternshipEngagement',
  DeleteLanguage = 'DeleteLanguage',
  DeleteLanguageEngagement = 'DeleteLanguageEngagement',
  DeleteLiteracyMaterial = 'DeleteLiteracyMaterial',
  DeleteLocation = 'DeleteLocation',
  DeleteOrganization = 'DeleteOrganization',
  DeletePartner = 'DeletePartner',
  DeletePartnership = 'DeletePartnership',
  DeletePost = 'DeletePost',
  DeleteProduct = 'DeleteProduct',
  DeleteProject = 'DeleteProject',
  DeleteProjectChangeRequest = 'DeleteProjectChangeRequest',
  DeleteProjectEngagement = 'DeleteProjectEngagement', // place holder if needed
  DeleteProjectMember = 'DeleteProjectMember',
  DeleteRegion = 'DeleteRegion',
  DeleteSong = 'DeleteSong',
  DeleteStory = 'DeleteStory',
  DeleteTranslationEngagement = 'DeleteTranslationEngagement',
  DeleteUnavailability = 'DeleteUnavailability',
  DeleteUser = 'DeleteUser',
  DeleteZone = 'DeleteZone',

  GrantAdministratorRole = 'GrantAdministratorRole',
  GrantConsultantManagerRole = 'GrantConsultantManagerRole',
  GrantConsultantRole = 'GrantConsultantRole',
  GrantControllerRole = 'GrantControllerRole',
  GrantFieldOperationsDirectorRole = 'GrantFieldOperationsDirectorRole',
  GrantFinancialAnalystRole = 'GrantFinancialAnalystRole',
  GrantFundraisingRole = 'GrantFundraisingRole',
  GrantInternRole = 'GrantInternRole',
  GrantLeadershipRole = 'GrantLeadershipRole',
  GrantLiaisonRole = 'GrantLiaisonRole',
  GrantMarketingRole = 'GrantMarketingRole',
  GrantMentorRole = 'GrantMentorRole',
  GrantPower = 'GrantPower',
  GrantProjectManagerRole = 'GrantProjectManagerRole',
  GrantRegionalCommunicationsCoordinatorRole = 'GrantRegionalCommunicationsCoordinatorRole',
  GrantRegionalDirectorRole = 'GrantRegionalDirectorRole',
  GrantRole = 'GrantRole',
  GrantStaffMemberRole = 'GrantStaffMemberRole',
  GrantTranslatorRole = 'GrantTranslatorRole',
}

registerEnumType(Powers, { name: 'Power' });
