/* eslint typescript-sort-keys/string-enum: "warn" */

import { registerEnumType } from '@nestjs/graphql';

export enum Powers {
  CreateBudget = 'CreateBudget',
  CreateBudgetRecord = 'CreateBudgetRecord',
  CreateCeremony = 'CreateCeremony',
  CreateDirectory = 'CreateDirectory',
  CreateEducation = 'CreateEducation',
  CreateEthnologueLanguage = 'CreateEthnologueLanguage',
  CreateFieldRegion = 'CreateFieldRegion',
  CreateFieldZone = 'CreateFieldZone',
  CreateFile = 'CreateFile',
  CreateFileVersion = 'CreateFileVersion',
  CreateFilm = 'CreateFilm',
  CreateFundingAccount = 'CreateFundingAccount',
  CreateInternshipEngagement = 'CreateInternshipEngagement',
  CreateLanguage = 'CreateLanguage',
  CreateLanguageEngagement = 'CreateLanguageEngagement',
  CreateLiteracyMaterial = 'CreateLiteracyMaterial',
  CreateLocation = 'CreateLocation',
  CreateOrganization = 'CreateOrganization',
  CreatePartner = 'CreatePartner',
  CreatePartnership = 'CreatePartnership',
  CreateProduct = 'CreateProduct',
  CreateProject = 'CreateProject',
  CreateProjectEngagement = 'CreateProjectEngagement', // place holder if needed
  CreateProjectMember = 'CreateProjectMember',
  CreateRegion = 'CreateRegion',
  CreateSong = 'CreateSong',
  CreateStory = 'CreateStory',
  CreateTranslationEngagement = 'CreateTranslationEngagement',
  CreateUnavailability = 'CreateUnavailability',
  CreateUser = 'CreateUser',
  CreateZone = 'CreateZone',
  DeleteLanguage = 'DeleteLanguage',
  DeleteProject = 'DeleteProject',
  GrantAdministratorRole = 'GrantAdministratorRole',
  GrantConsultuntManagerRole = 'GrantConsultuntManagerRole',
  GrantControllerRole = 'GrantControllerRole',
  GrantFieldOperationsDirectorRole = 'GrantFieldOperationsDirectorRole',
  GrantFinancialAnalystRole = 'GrantFinancialAnalystRole',
  GrantPower = 'GrantPower',
  GrantProjectManagerRole = 'GrantProjectManagerRole',
  GrantRegionalDirectorRole = 'GrantRegionalDirectorRole',
  GrantRole = 'GrantRole',
}

registerEnumType(Powers, { name: 'Power' });
