// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _Mixin from "./Mixin";
import type * as _std from "./std";
import type * as _default from "./default";
export type $EmailTokenλShape = $.typeutil.flatten<_Mixin.$TimestampedλShape & {
  "email": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "token": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $EmailToken = $.ObjectType<"Auth::EmailToken", $EmailTokenλShape, null, [
  ..._Mixin.$Timestamped['__exclusives__'],
  {token: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "Auth::EmailToken">;
const $EmailToken = $.makeType<$EmailToken>(_.spec, "353bbc86-01a9-11f0-8c00-6dec7f5c139a", _.syntax.literal);

const EmailToken: $.$expr_PathNode<$.TypeSet<$EmailToken, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($EmailToken, $.Cardinality.Many), null);

export type $IdentityλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "user": $.LinkDesc<_default.$User, $.Cardinality.One, {}, true, false,  false, false>;
  "passwordHash": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Identity = $.ObjectType<"Auth::Identity", $IdentityλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {user: {__element__: _default.$User, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "Auth::Identity">;
const $Identity = $.makeType<$Identity>(_.spec, "353e9b68-01a9-11f0-9040-45c99176890c", _.syntax.literal);

const Identity: $.$expr_PathNode<$.TypeSet<$Identity, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Identity, $.Cardinality.Many), null);

export type $SessionλShape = $.typeutil.flatten<_Mixin.$TimestampedλShape & {
  "user": $.LinkDesc<_default.$User, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "token": $.PropertyDesc<_std.$str, $.Cardinality.One, true, false, false, false>;
}>;
type $Session = $.ObjectType<"Auth::Session", $SessionλShape, null, [
  ..._Mixin.$Timestamped['__exclusives__'],
  {token: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "Auth::Session">;
const $Session = $.makeType<$Session>(_.spec, "35407b22-01a9-11f0-be38-ff8a37d4f233", _.syntax.literal);

const Session: $.$expr_PathNode<$.TypeSet<$Session, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Session, $.Cardinality.Many), null);



export { $EmailToken, EmailToken, $Identity, Identity, $Session, Session };

type __defaultExports = {
  "EmailToken": typeof EmailToken;
  "Identity": typeof Identity;
  "Session": typeof Session
};
const __defaultExports: __defaultExports = {
  "EmailToken": EmailToken,
  "Identity": Identity,
  "Session": Session
};
export default __defaultExports;
