// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _Project from "./Project";
import type * as _std from "./std";
import type * as _default from "./default";
export type $Status = {
  "Pending": $.$expr_Literal<$Status>;
  "Current": $.$expr_Literal<$Status>;
  "Superceded": $.$expr_Literal<$Status>;
  "Rejected": $.$expr_Literal<$Status>;
} & $.EnumType<"Budget::Status", ["Pending", "Current", "Superceded", "Rejected"]>;
const Status: $Status = $.makeType<$Status>(_.spec, "47b0ce92-01a9-11f0-b0e1-89054f256929", _.syntax.literal);

export type $RecordλShape = $.typeutil.flatten<_Project.$ChildλShape & {
  "fiscalYear": $.PropertyDesc<_std.$int16, $.Cardinality.One, false, false, true, false>;
  "amount": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "budget": $.LinkDesc<_default.$Budget, $.Cardinality.One, {}, false, false,  true, false>;
  "organization": $.LinkDesc<_default.$Organization, $.Cardinality.One, {}, false, false,  true, false>;
  "<records[is Budget]": $.LinkDesc<_default.$Budget, $.Cardinality.Many, {}, false, false,  false, false>;
  "<records": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Record = $.ObjectType<"Budget::Record", $RecordλShape, null, [
  ..._Project.$Child['__exclusives__'],
  {budget: {__element__: _default.$Budget, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },fiscalYear: {__element__: _std.$int16, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },organization: {__element__: _default.$Organization, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "Budget::Record">;
const $Record = $.makeType<$Record>(_.spec, "479e4268-01a9-11f0-a47e-3b1faefd15e6", _.syntax.literal);

const Record: $.$expr_PathNode<$.TypeSet<$Record, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Record, $.Cardinality.Many), null);



export { Status, $Record, Record };

type __defaultExports = {
  "Status": typeof Status;
  "Record": typeof Record
};
const __defaultExports: __defaultExports = {
  "Status": Status,
  "Record": Record
};
export default __defaultExports;
