// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _Project from "./Project";
import type * as _default from "./default";
import type * as _cal from "./cal";
import type * as _std from "./std";
export type $AIAssistedTranslation = {
  "Unknown": $.$expr_Literal<$AIAssistedTranslation>;
  "None": $.$expr_Literal<$AIAssistedTranslation>;
  "Draft": $.$expr_Literal<$AIAssistedTranslation>;
  "Check": $.$expr_Literal<$AIAssistedTranslation>;
  "DraftAndCheck": $.$expr_Literal<$AIAssistedTranslation>;
  "Other": $.$expr_Literal<$AIAssistedTranslation>;
} & $.EnumType<"Engagement::AIAssistedTranslation", ["Unknown", "None", "Draft", "Check", "DraftAndCheck", "Other"]>;
const AIAssistedTranslation: $AIAssistedTranslation = $.makeType<$AIAssistedTranslation>(_.spec, "eeeaaf54-0670-11f0-820f-a5f714233240", _.syntax.literal);

export type $InternPosition = {
  "ConsultantInTraining": $.$expr_Literal<$InternPosition>;
  "MidLevelQualityAssurance": $.$expr_Literal<$InternPosition>;
  "LeadershipDevelopment": $.$expr_Literal<$InternPosition>;
  "Mobilization": $.$expr_Literal<$InternPosition>;
  "Personnel": $.$expr_Literal<$InternPosition>;
  "Communication": $.$expr_Literal<$InternPosition>;
  "Administration": $.$expr_Literal<$InternPosition>;
  "Technology": $.$expr_Literal<$InternPosition>;
  "Finance": $.$expr_Literal<$InternPosition>;
  "LanguageProgramManager": $.$expr_Literal<$InternPosition>;
  "Literacy": $.$expr_Literal<$InternPosition>;
  "OralityFacilitator": $.$expr_Literal<$InternPosition>;
  "ScriptureEngagement": $.$expr_Literal<$InternPosition>;
  "OtherAttached": $.$expr_Literal<$InternPosition>;
  "OtherTranslationCapacity": $.$expr_Literal<$InternPosition>;
  "OtherPartnershipCapacity": $.$expr_Literal<$InternPosition>;
  "ExegeticalFacilitator": $.$expr_Literal<$InternPosition>;
  "TranslationFacilitator": $.$expr_Literal<$InternPosition>;
} & $.EnumType<"Engagement::InternPosition", ["ConsultantInTraining", "MidLevelQualityAssurance", "LeadershipDevelopment", "Mobilization", "Personnel", "Communication", "Administration", "Technology", "Finance", "LanguageProgramManager", "Literacy", "OralityFacilitator", "ScriptureEngagement", "OtherAttached", "OtherTranslationCapacity", "OtherPartnershipCapacity", "ExegeticalFacilitator", "TranslationFacilitator"]>;
const InternPosition: $InternPosition = $.makeType<$InternPosition>(_.spec, "088937ba-0670-11f0-9cc4-1bbcf6b2e66c", _.syntax.literal);

export type $Status = {
  "InDevelopment": $.$expr_Literal<$Status>;
  "DidNotDevelop": $.$expr_Literal<$Status>;
  "Rejected": $.$expr_Literal<$Status>;
  "Active": $.$expr_Literal<$Status>;
  "DiscussingTermination": $.$expr_Literal<$Status>;
  "DiscussingReactivation": $.$expr_Literal<$Status>;
  "DiscussingChangeToPlan": $.$expr_Literal<$Status>;
  "DiscussingSuspension": $.$expr_Literal<$Status>;
  "FinalizingCompletion": $.$expr_Literal<$Status>;
  "ActiveChangedPlan": $.$expr_Literal<$Status>;
  "Suspended": $.$expr_Literal<$Status>;
  "Terminated": $.$expr_Literal<$Status>;
  "Completed": $.$expr_Literal<$Status>;
  "Converted": $.$expr_Literal<$Status>;
  "Unapproved": $.$expr_Literal<$Status>;
  "Transferred": $.$expr_Literal<$Status>;
  "NotRenewed": $.$expr_Literal<$Status>;
} & $.EnumType<"Engagement::Status", ["InDevelopment", "DidNotDevelop", "Rejected", "Active", "DiscussingTermination", "DiscussingReactivation", "DiscussingChangeToPlan", "DiscussingSuspension", "FinalizingCompletion", "ActiveChangedPlan", "Suspended", "Terminated", "Completed", "Converted", "Unapproved", "Transferred", "NotRenewed"]>;
const Status: $Status = $.makeType<$Status>(_.spec, "088940b6-0670-11f0-97bd-2df805ea0613", _.syntax.literal);

export type $ChildλShape = $.typeutil.flatten<_Project.$ChildλShape & {
  "engagement": $.LinkDesc<_default.$Engagement, $.Cardinality.One, {}, false, false,  true, false>;
}>;
type $Child = $.ObjectType<"Engagement::Child", $ChildλShape, null, [
  ..._Project.$Child['__exclusives__'],
], "Engagement::CertificationCeremony" | "Engagement::DedicationCeremony" | "Product::PartnershipProducingMedium" | "ProgressReport::CommunityStory" | "ProgressReport::Highlight" | "ProgressReport::Media" | "ProgressReport::TeamNews" | "ProgressReport::VarianceExplanation" | "default::DerivativeScriptureProduct" | "default::DirectScriptureProduct" | "default::OtherProduct" | "default::ProgressReport">;
const $Child = $.makeType<$Child>(_.spec, "08665c04-0670-11f0-930a-1fdfaa995689", _.syntax.literal);

const Child: $.$expr_PathNode<$.TypeSet<$Child, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Child, $.Cardinality.Many), null);

export type $CeremonyλShape = $.typeutil.flatten<$ChildλShape & {
  "actualDate": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "estimatedDate": $.PropertyDesc<_cal.$local_date, $.Cardinality.AtMostOne, false, false, false, false>;
  "planned": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, false, false, true>;
  "<ceremony[is Engagement]": $.LinkDesc<_default.$Engagement, $.Cardinality.Many, {}, false, false,  false, false>;
  "<ceremony[is LanguageEngagement]": $.LinkDesc<_default.$LanguageEngagement, $.Cardinality.Many, {}, false, false,  false, false>;
  "<ceremony[is InternshipEngagement]": $.LinkDesc<_default.$InternshipEngagement, $.Cardinality.Many, {}, false, false,  false, false>;
  "<ceremony": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Ceremony = $.ObjectType<"Engagement::Ceremony", $CeremonyλShape, null, [
  ...$Child['__exclusives__'],
], "Engagement::CertificationCeremony" | "Engagement::DedicationCeremony">;
const $Ceremony = $.makeType<$Ceremony>(_.spec, "086d02e8-0670-11f0-8693-dfdff438ec19", _.syntax.literal);

const Ceremony: $.$expr_PathNode<$.TypeSet<$Ceremony, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Ceremony, $.Cardinality.Many), null);

export type $CertificationCeremonyλShape = $.typeutil.flatten<$CeremonyλShape & {
}>;
type $CertificationCeremony = $.ObjectType<"Engagement::CertificationCeremony", $CertificationCeremonyλShape, null, [
  ...$Ceremony['__exclusives__'],
], "Engagement::CertificationCeremony">;
const $CertificationCeremony = $.makeType<$CertificationCeremony>(_.spec, "0873fc1a-0670-11f0-99ae-7d13e9895cfc", _.syntax.literal);

const CertificationCeremony: $.$expr_PathNode<$.TypeSet<$CertificationCeremony, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CertificationCeremony, $.Cardinality.Many), null);

export type $DedicationCeremonyλShape = $.typeutil.flatten<$CeremonyλShape & {
}>;
type $DedicationCeremony = $.ObjectType<"Engagement::DedicationCeremony", $DedicationCeremonyλShape, null, [
  ...$Ceremony['__exclusives__'],
], "Engagement::DedicationCeremony">;
const $DedicationCeremony = $.makeType<$DedicationCeremony>(_.spec, "088233fc-0670-11f0-a10e-9db4c5947419", _.syntax.literal);

const DedicationCeremony: $.$expr_PathNode<$.TypeSet<$DedicationCeremony, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($DedicationCeremony, $.Cardinality.Many), null);



export { AIAssistedTranslation, InternPosition, Status, $Child, Child, $Ceremony, Ceremony, $CertificationCeremony, CertificationCeremony, $DedicationCeremony, DedicationCeremony };

type __defaultExports = {
  "AIAssistedTranslation": typeof AIAssistedTranslation;
  "InternPosition": typeof InternPosition;
  "Status": typeof Status;
  "Child": typeof Child;
  "Ceremony": typeof Ceremony;
  "CertificationCeremony": typeof CertificationCeremony;
  "DedicationCeremony": typeof DedicationCeremony
};
const __defaultExports: __defaultExports = {
  "AIAssistedTranslation": AIAssistedTranslation,
  "InternPosition": InternPosition,
  "Status": Status,
  "Child": Child,
  "Ceremony": Ceremony,
  "CertificationCeremony": CertificationCeremony,
  "DedicationCeremony": DedicationCeremony
};
export default __defaultExports;
