// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _Project from "./Project";
import type * as _default from "./default";
export type $code = $.ScalarType<"std::str", string>;
const code: $.scalarTypeWithConstructor<_std.$str, never> = $.makeType<$.scalarTypeWithConstructor<_std.$str, never>>(_.spec, "34951228-01a9-11f0-8c26-6dc068bae54b", _.syntax.literal);

export type $LanguageλShape = $.typeutil.flatten<_Project.$ContextAwareλShape & {
  "language": $.LinkDesc<_default.$Language, $.Cardinality.One, {}, true, false,  false, false>;
  "population": $.PropertyDesc<_default.$population, $.Cardinality.AtMostOne, false, false, false, false>;
  "code": $.PropertyDesc<$code, $.Cardinality.AtMostOne, true, false, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "provisionalCode": $.PropertyDesc<$code, $.Cardinality.AtMostOne, true, false, false, false>;
  "<ethnologue[is Language]": $.LinkDesc<_default.$Language, $.Cardinality.Many, {}, false, false,  false, false>;
  "<ethnologue": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Language = $.ObjectType<"Ethnologue::Language", $LanguageλShape, null, [
  ..._Project.$ContextAware['__exclusives__'],
  {language: {__element__: _default.$Language, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {code: {__element__: $code, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
  {provisionalCode: {__element__: $code, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "Ethnologue::Language">;
const $Language = $.makeType<$Language>(_.spec, "34958e9c-01a9-11f0-ae74-85ec9b1077bd", _.syntax.literal);

const Language: $.$expr_PathNode<$.TypeSet<$Language, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Language, $.Cardinality.Many), null);



export { code, $Language, Language };

type __defaultExports = {
  "code": typeof code;
  "Language": typeof Language
};
const __defaultExports: __defaultExports = {
  "code": code,
  "Language": Language
};
export default __defaultExports;
