// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
export type $Milestone = {
  "Unknown": $.$expr_Literal<$Milestone>;
  "None": $.$expr_Literal<$Milestone>;
  "OldTestament": $.$expr_Literal<$Milestone>;
  "NewTestament": $.$expr_Literal<$Milestone>;
  "FullBible": $.$expr_Literal<$Milestone>;
} & $.EnumType<"Language::Milestone", ["Unknown", "None", "OldTestament", "NewTestament", "FullBible"]>;
const Milestone: $Milestone = $.makeType<$Milestone>(_.spec, "ed3fd3fa-0670-11f0-9c51-8943b988df8e", _.syntax.literal);



export { Milestone };

type __defaultExports = {
  "Milestone": typeof Milestone
};
const __defaultExports: __defaultExports = {
  "Milestone": Milestone
};
export default __defaultExports;
