// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _std from "./std";
import type * as _default from "./default";
export type $TimestampedλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "createdAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
  "modifiedAt": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, false, true>;
}>;
type $Timestamped = $.ObjectType<"Mixin::Timestamped", $TimestampedλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "Auth::EmailToken" | "Auth::Session" | "Budget::Record" | "Comments::Comment" | "Comments::Thread" | "Engagement::CertificationCeremony" | "Engagement::DedicationCeremony" | "File::Version" | "Notification::CommentViaMembership" | "Notification::CommentViaMention" | "Notification::System" | "Product::PartnershipProducingMedium" | "ProgressReport::CommunityStory" | "ProgressReport::Highlight" | "ProgressReport::Media" | "ProgressReport::ProductProgress::Step" | "ProgressReport::TeamNews" | "ProgressReport::VarianceExplanation" | "Project::Member" | "Prompt::VariantResponse" | "User::Education" | "User::Unavailability" | "default::Budget" | "default::DerivativeScriptureProduct" | "default::DirectScriptureProduct" | "default::Directory" | "default::EthnoArt" | "default::FieldRegion" | "default::FieldZone" | "default::File" | "default::Film" | "default::FinancialReport" | "default::FundingAccount" | "default::InternshipEngagement" | "default::InternshipProject" | "default::Language" | "default::LanguageEngagement" | "default::Location" | "default::MomentumTranslationProject" | "default::MultiplicationTranslationProject" | "default::NarrativeReport" | "default::Organization" | "default::OtherProduct" | "default::Partner" | "default::Partnership" | "default::Post" | "default::ProgressReport" | "default::Story" | "default::User" | "default::currentUser">;
const $Timestamped = $.makeType<$Timestamped>(_.spec, "319ce6f4-01a9-11f0-a37a-3bb59f215990", _.syntax.literal);

const Timestamped: $.$expr_PathNode<$.TypeSet<$Timestamped, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Timestamped, $.Cardinality.Many), null);

export type $AuditedλShape = $.typeutil.flatten<$TimestampedλShape & {
  "createdBy": $.LinkDesc<_default.$Actor, $.Cardinality.One, {}, false, false,  true, true>;
  "modifiedBy": $.LinkDesc<_default.$Actor, $.Cardinality.One, {}, false, false,  false, true>;
  "isCreator": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, true, false, false>;
}>;
type $Audited = $.ObjectType<"Mixin::Audited", $AuditedλShape, null, [
  ...$Timestamped['__exclusives__'],
], "Budget::Record" | "Comments::Comment" | "Comments::Thread" | "Engagement::CertificationCeremony" | "Engagement::DedicationCeremony" | "File::Version" | "Notification::CommentViaMembership" | "Notification::CommentViaMention" | "Notification::System" | "Product::PartnershipProducingMedium" | "ProgressReport::CommunityStory" | "ProgressReport::Highlight" | "ProgressReport::Media" | "ProgressReport::TeamNews" | "ProgressReport::VarianceExplanation" | "Project::Member" | "Prompt::VariantResponse" | "User::Education" | "User::Unavailability" | "default::Budget" | "default::DerivativeScriptureProduct" | "default::DirectScriptureProduct" | "default::Directory" | "default::EthnoArt" | "default::FieldRegion" | "default::FieldZone" | "default::File" | "default::Film" | "default::FinancialReport" | "default::FundingAccount" | "default::InternshipEngagement" | "default::InternshipProject" | "default::Language" | "default::LanguageEngagement" | "default::Location" | "default::MomentumTranslationProject" | "default::MultiplicationTranslationProject" | "default::NarrativeReport" | "default::Organization" | "default::OtherProduct" | "default::Partner" | "default::Partnership" | "default::Post" | "default::ProgressReport" | "default::Story" | "default::User" | "default::currentUser">;
const $Audited = $.makeType<$Audited>(_.spec, "319f8c6a-01a9-11f0-9cbc-89aa73d0401b", _.syntax.literal);

const Audited: $.$expr_PathNode<$.TypeSet<$Audited, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Audited, $.Cardinality.Many), null);

export type $EmbeddedλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "container": $.LinkDesc<_default.$Resource, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Embedded = $.ObjectType<"Mixin::Embedded", $EmbeddedλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "Comments::Thread" | "ProgressReport::CommunityStory" | "ProgressReport::Highlight" | "ProgressReport::TeamNews" | "default::FinancialReport" | "default::NarrativeReport" | "default::Post" | "default::ProgressReport">;
const $Embedded = $.makeType<$Embedded>(_.spec, "3542fe2e-01a9-11f0-b700-434a7332f55d", _.syntax.literal);

const Embedded: $.$expr_PathNode<$.TypeSet<$Embedded, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Embedded, $.Cardinality.Many), null);

export type $NamedλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "name": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $Named = $.ObjectType<"Mixin::Named", $NamedλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "File::Version" | "default::Directory" | "default::EthnoArt" | "default::FieldRegion" | "default::FieldZone" | "default::File" | "default::Film" | "default::FundingAccount" | "default::InternshipProject" | "default::Language" | "default::Location" | "default::MomentumTranslationProject" | "default::MultiplicationTranslationProject" | "default::Organization" | "default::Partner" | "default::Story" | "default::SystemAgent">;
const $Named = $.makeType<$Named>(_.spec, "31994c42-01a9-11f0-80be-43469fb4b091", _.syntax.literal);

const Named: $.$expr_PathNode<$.TypeSet<$Named, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Named, $.Cardinality.Many), null);

export type $PinnableλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "pinned": $.PropertyDesc<_std.$bool, $.Cardinality.One, false, true, false, false>;
  "<pins[is User]": $.LinkDesc<_default.$User, $.Cardinality.Many, {}, false, false,  false, false>;
  "<pins[is currentUser]": $.LinkDesc<_default.$currentUser, $.Cardinality.Many, {}, false, false,  false, false>;
  "<pins": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Pinnable = $.ObjectType<"Mixin::Pinnable", $PinnableλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::InternshipProject" | "default::Language" | "default::MomentumTranslationProject" | "default::MultiplicationTranslationProject" | "default::Partner" | "default::User" | "default::currentUser">;
const $Pinnable = $.makeType<$Pinnable>(_.spec, "31ac8a0a-01a9-11f0-9311-119da8e47b79", _.syntax.literal);

const Pinnable: $.$expr_PathNode<$.TypeSet<$Pinnable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Pinnable, $.Cardinality.Many), null);

export type $PostableλShape = $.typeutil.flatten<Omit<_default.$ResourceλShape, "<container"> & {
  "posts": $.LinkDesc<_default.$Post, $.Cardinality.Many, {}, false, true,  false, false>;
  "<container[is Post]": $.LinkDesc<_default.$Post, $.Cardinality.Many, {}, false, false,  false, false>;
  "<container": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Postable = $.ObjectType<"Mixin::Postable", $PostableλShape, null, [
  ..._default.$Resource['__exclusives__'],
], "default::InternshipProject" | "default::Language" | "default::MomentumTranslationProject" | "default::MultiplicationTranslationProject" | "default::Partner">;
const $Postable = $.makeType<$Postable>(_.spec, "adca01da-01a9-11f0-b152-213c8ae8a2cb", _.syntax.literal);

const Postable: $.$expr_PathNode<$.TypeSet<$Postable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Postable, $.Cardinality.Many), null);

export type $TaggableλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "tags": $.PropertyDesc<_std.$str, $.Cardinality.Many, false, false, false, false>;
}>;
type $Taggable = $.ObjectType<"Mixin::Taggable", $TaggableλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "default::InternshipProject" | "default::Language" | "default::MomentumTranslationProject" | "default::MultiplicationTranslationProject" | "default::Partner">;
const $Taggable = $.makeType<$Taggable>(_.spec, "319baa96-01a9-11f0-b16d-81ee7de06a65", _.syntax.literal);

const Taggable: $.$expr_PathNode<$.TypeSet<$Taggable, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Taggable, $.Cardinality.Many), null);



export { $Timestamped, Timestamped, $Audited, Audited, $Embedded, Embedded, $Named, Named, $Pinnable, Pinnable, $Postable, Postable, $Taggable, Taggable };

type __defaultExports = {
  "Timestamped": typeof Timestamped;
  "Audited": typeof Audited;
  "Embedded": typeof Embedded;
  "Named": typeof Named;
  "Pinnable": typeof Pinnable;
  "Postable": typeof Postable;
  "Taggable": typeof Taggable
};
const __defaultExports: __defaultExports = {
  "Timestamped": Timestamped,
  "Audited": Audited,
  "Embedded": Embedded,
  "Named": Named,
  "Pinnable": Pinnable,
  "Postable": Postable,
  "Taggable": Taggable
};
export default __defaultExports;
