// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _default from "./default";
import type * as _Comments from "./Comments";
import type * as _std from "./std";
export type $CommentλShape = $.typeutil.flatten<_default.$NotificationλShape & {
  "comment": $.LinkDesc<_Comments.$Comment, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Comment = $.ObjectType<"Notification::Comment", $CommentλShape, null, [
  ..._default.$Notification['__exclusives__'],
], "Notification::CommentViaMembership" | "Notification::CommentViaMention">;
const $Comment = $.makeType<$Comment>(_.spec, "bb99df64-01aa-11f0-99c1-8111746cd019", _.syntax.literal);

const Comment: $.$expr_PathNode<$.TypeSet<$Comment, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Comment, $.Cardinality.Many), null);

export type $CommentViaMembershipλShape = $.typeutil.flatten<$CommentλShape & {
}>;
type $CommentViaMembership = $.ObjectType<"Notification::CommentViaMembership", $CommentViaMembershipλShape, null, [
  ...$Comment['__exclusives__'],
], "Notification::CommentViaMembership">;
const $CommentViaMembership = $.makeType<$CommentViaMembership>(_.spec, "bc01d484-01aa-11f0-936c-6b6c0a9eda45", _.syntax.literal);

const CommentViaMembership: $.$expr_PathNode<$.TypeSet<$CommentViaMembership, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CommentViaMembership, $.Cardinality.Many), null);

export type $CommentViaMentionλShape = $.typeutil.flatten<$CommentλShape & {
}>;
type $CommentViaMention = $.ObjectType<"Notification::CommentViaMention", $CommentViaMentionλShape, null, [
  ...$Comment['__exclusives__'],
], "Notification::CommentViaMention">;
const $CommentViaMention = $.makeType<$CommentViaMention>(_.spec, "bc478628-01aa-11f0-b7a2-fd9155ffe5a7", _.syntax.literal);

const CommentViaMention: $.$expr_PathNode<$.TypeSet<$CommentViaMention, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CommentViaMention, $.Cardinality.Many), null);

export type $RecipientλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "notification": $.LinkDesc<_default.$Notification, $.Cardinality.One, {}, false, false,  false, false>;
  "user": $.LinkDesc<_default.$User, $.Cardinality.One, {}, false, false,  false, false>;
  "readAt": $.PropertyDesc<_std.$datetime, $.Cardinality.AtMostOne, false, false, false, false>;
  "<recipients[is Notification::CommentViaMembership]": $.LinkDesc<$CommentViaMembership, $.Cardinality.Many, {}, false, false,  false, false>;
  "<currentRecipient[is Notification::CommentViaMembership]": $.LinkDesc<$CommentViaMembership, $.Cardinality.Many, {}, false, false,  false, false>;
  "<recipients[is Notification::CommentViaMention]": $.LinkDesc<$CommentViaMention, $.Cardinality.Many, {}, false, false,  false, false>;
  "<currentRecipient[is Notification::CommentViaMention]": $.LinkDesc<$CommentViaMention, $.Cardinality.Many, {}, false, false,  false, false>;
  "<recipients[is Notification]": $.LinkDesc<_default.$Notification, $.Cardinality.Many, {}, false, false,  false, false>;
  "<recipients[is Notification::Comment]": $.LinkDesc<$Comment, $.Cardinality.Many, {}, false, false,  false, false>;
  "<currentRecipient[is Notification]": $.LinkDesc<_default.$Notification, $.Cardinality.Many, {}, false, false,  false, false>;
  "<currentRecipient[is Notification::Comment]": $.LinkDesc<$Comment, $.Cardinality.Many, {}, false, false,  false, false>;
  "<recipients[is Notification::System]": $.LinkDesc<$System, $.Cardinality.Many, {}, false, false,  false, false>;
  "<currentRecipient[is Notification::System]": $.LinkDesc<$System, $.Cardinality.Many, {}, false, false,  false, false>;
  "<currentRecipient": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<recipients": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $Recipient = $.ObjectType<"Notification::Recipient", $RecipientλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "Notification::Recipient">;
const $Recipient = $.makeType<$Recipient>(_.spec, "bbb5285a-01aa-11f0-a321-211cd9a04bf6", _.syntax.literal);

const Recipient: $.$expr_PathNode<$.TypeSet<$Recipient, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Recipient, $.Cardinality.Many), null);

export type $SystemλShape = $.typeutil.flatten<_default.$NotificationλShape & {
  "message": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
}>;
type $System = $.ObjectType<"Notification::System", $SystemλShape, null, [
  ..._default.$Notification['__exclusives__'],
], "Notification::System">;
const $System = $.makeType<$System>(_.spec, "bc8a5eee-01aa-11f0-8063-41f78fb0ae90", _.syntax.literal);

const System: $.$expr_PathNode<$.TypeSet<$System, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($System, $.Cardinality.Many), null);



export { $Comment, Comment, $CommentViaMembership, CommentViaMembership, $CommentViaMention, CommentViaMention, $Recipient, Recipient, $System, System };

type __defaultExports = {
  "Comment": typeof Comment;
  "CommentViaMembership": typeof CommentViaMembership;
  "CommentViaMention": typeof CommentViaMention;
  "Recipient": typeof Recipient;
  "System": typeof System
};
const __defaultExports: __defaultExports = {
  "Comment": Comment,
  "CommentViaMembership": CommentViaMembership,
  "CommentViaMention": CommentViaMention,
  "Recipient": Recipient,
  "System": System
};
export default __defaultExports;
