// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
export type $Type = {
  "Managing": $.$expr_Literal<$Type>;
  "Funding": $.$expr_Literal<$Type>;
  "Impact": $.$expr_Literal<$Type>;
  "Technical": $.$expr_Literal<$Type>;
  "Resource": $.$expr_Literal<$Type>;
} & $.EnumType<"Partner::Type", ["Managing", "Funding", "Impact", "Technical", "Resource"]>;
const Type: $Type = $.makeType<$Type>(_.spec, "4805262c-01a9-11f0-a209-a920640b7e19", _.syntax.literal);



export { Type };

type __defaultExports = {
  "Type": typeof Type
};
const __defaultExports: __defaultExports = {
  "Type": Type
};
export default __defaultExports;
