// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
export type $AgreementStatus = {
  "NotAttached": $.$expr_Literal<$AgreementStatus>;
  "AwaitingSignature": $.$expr_Literal<$AgreementStatus>;
  "Signed": $.$expr_Literal<$AgreementStatus>;
} & $.EnumType<"Partnership::AgreementStatus", ["NotAttached", "AwaitingSignature", "Signed"]>;
const AgreementStatus: $AgreementStatus = $.makeType<$AgreementStatus>(_.spec, "1c875d32-0670-11f0-aa04-733ce39f88a6", _.syntax.literal);

export type $FinancialReportingType = {
  "Funded": $.$expr_Literal<$FinancialReportingType>;
  "FieldEngaged": $.$expr_Literal<$FinancialReportingType>;
  "Hybrid": $.$expr_Literal<$FinancialReportingType>;
} & $.EnumType<"Partnership::FinancialReportingType", ["Funded", "FieldEngaged", "Hybrid"]>;
const FinancialReportingType: $FinancialReportingType = $.makeType<$FinancialReportingType>(_.spec, "1c87655c-0670-11f0-8311-7b5c655ec225", _.syntax.literal);



export { AgreementStatus, FinancialReportingType };

type __defaultExports = {
  "AgreementStatus": typeof AgreementStatus;
  "FinancialReportingType": typeof FinancialReportingType
};
const __defaultExports: __defaultExports = {
  "AgreementStatus": AgreementStatus,
  "FinancialReportingType": FinancialReportingType
};
export default __defaultExports;
