// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
export type $Shareability = {
  "Membership": $.$expr_Literal<$Shareability>;
  "Internal": $.$expr_Literal<$Shareability>;
  "AskToShareExternally": $.$expr_Literal<$Shareability>;
  "External": $.$expr_Literal<$Shareability>;
} & $.EnumType<"Post::Shareability", ["Membership", "Internal", "AskToShareExternally", "External"]>;
const Shareability: $Shareability = $.makeType<$Shareability>(_.spec, "dc25f03e-01a9-11f0-b844-c9d631227d51", _.syntax.literal);

export type $Type = {
  "Note": $.$expr_Literal<$Type>;
  "Story": $.$expr_Literal<$Type>;
  "Prayer": $.$expr_Literal<$Type>;
} & $.EnumType<"Post::Type", ["Note", "Story", "Prayer"]>;
const Type: $Type = $.makeType<$Type>(_.spec, "dc260b28-01a9-11f0-9f1d-21159da5de65", _.syntax.literal);



export { Shareability, Type };

type __defaultExports = {
  "Shareability": typeof Shareability;
  "Type": typeof Type
};
const __defaultExports: __defaultExports = {
  "Shareability": Shareability,
  "Type": Type
};
export default __defaultExports;
