// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _Engagement from "./Engagement";
import type * as _default from "./default";
export type $Medium = {
  "Print": $.$expr_Literal<$Medium>;
  "Web": $.$expr_Literal<$Medium>;
  "EBook": $.$expr_Literal<$Medium>;
  "App": $.$expr_Literal<$Medium>;
  "TrainedStoryTellers": $.$expr_Literal<$Medium>;
  "Audio": $.$expr_Literal<$Medium>;
  "Video": $.$expr_Literal<$Medium>;
  "Other": $.$expr_Literal<$Medium>;
} & $.EnumType<"Product::Medium", ["Print", "Web", "EBook", "App", "TrainedStoryTellers", "Audio", "Video", "Other"]>;
const Medium: $Medium = $.makeType<$Medium>(_.spec, "1c7852e2-0670-11f0-9ed3-81a49e3e2dee", _.syntax.literal);

export type $Methodology = {
  "Paratext": $.$expr_Literal<$Methodology>;
  "OtherWritten": $.$expr_Literal<$Methodology>;
  "Render": $.$expr_Literal<$Methodology>;
  "Audacity": $.$expr_Literal<$Methodology>;
  "AdobeAudition": $.$expr_Literal<$Methodology>;
  "OtherOralTranslation": $.$expr_Literal<$Methodology>;
  "StoryTogether": $.$expr_Literal<$Methodology>;
  "SeedCompanyMethod": $.$expr_Literal<$Methodology>;
  "OneStory": $.$expr_Literal<$Methodology>;
  "Craft2Tell": $.$expr_Literal<$Methodology>;
  "OtherOralStories": $.$expr_Literal<$Methodology>;
  "Film": $.$expr_Literal<$Methodology>;
  "SignLanguage": $.$expr_Literal<$Methodology>;
  "OtherVisual": $.$expr_Literal<$Methodology>;
} & $.EnumType<"Product::Methodology", ["Paratext", "OtherWritten", "Render", "Audacity", "AdobeAudition", "OtherOralTranslation", "StoryTogether", "SeedCompanyMethod", "OneStory", "Craft2Tell", "OtherOralStories", "Film", "SignLanguage", "OtherVisual"]>;
const Methodology: $Methodology = $.makeType<$Methodology>(_.spec, "08894908-0670-11f0-a6f4-01cf3515ad50", _.syntax.literal);

export type $ProgressMeasurement = {
  "Number": $.$expr_Literal<$ProgressMeasurement>;
  "Percent": $.$expr_Literal<$ProgressMeasurement>;
  "Boolean": $.$expr_Literal<$ProgressMeasurement>;
} & $.EnumType<"Product::ProgressMeasurement", ["Number", "Percent", "Boolean"]>;
const ProgressMeasurement: $ProgressMeasurement = $.makeType<$ProgressMeasurement>(_.spec, "1d84853e-0670-11f0-a303-591522c7d674", _.syntax.literal);

export type $Purpose = {
  "EvangelismChurchPlanting": $.$expr_Literal<$Purpose>;
  "ChurchLife": $.$expr_Literal<$Purpose>;
  "ChurchMaturity": $.$expr_Literal<$Purpose>;
  "SocialIssues": $.$expr_Literal<$Purpose>;
  "Discipleship": $.$expr_Literal<$Purpose>;
} & $.EnumType<"Product::Purpose", ["EvangelismChurchPlanting", "ChurchLife", "ChurchMaturity", "SocialIssues", "Discipleship"]>;
const Purpose: $Purpose = $.makeType<$Purpose>(_.spec, "1d848dea-0670-11f0-9863-7368d76744ca", _.syntax.literal);

export type $Step = {
  "ExegesisAndFirstDraft": $.$expr_Literal<$Step>;
  "TeamCheck": $.$expr_Literal<$Step>;
  "CommunityTesting": $.$expr_Literal<$Step>;
  "BackTranslation": $.$expr_Literal<$Step>;
  "ConsultantCheck": $.$expr_Literal<$Step>;
  "InternalizationAndDrafting": $.$expr_Literal<$Step>;
  "PeerRevision": $.$expr_Literal<$Step>;
  "ConsistencyCheckAndFinalEdits": $.$expr_Literal<$Step>;
  "Craft": $.$expr_Literal<$Step>;
  "Test": $.$expr_Literal<$Step>;
  "Check": $.$expr_Literal<$Step>;
  "Record": $.$expr_Literal<$Step>;
  "Develop": $.$expr_Literal<$Step>;
  "Translate": $.$expr_Literal<$Step>;
  "Completed": $.$expr_Literal<$Step>;
} & $.EnumType<"Product::Step", ["ExegesisAndFirstDraft", "TeamCheck", "CommunityTesting", "BackTranslation", "ConsultantCheck", "InternalizationAndDrafting", "PeerRevision", "ConsistencyCheckAndFinalEdits", "Craft", "Test", "Check", "Record", "Develop", "Translate", "Completed"]>;
const Step: $Step = $.makeType<$Step>(_.spec, "1d7b2dae-0670-11f0-b8ed-09e76eb55e24", _.syntax.literal);

export type $PartnershipProducingMediumλShape = $.typeutil.flatten<_Engagement.$ChildλShape & {
  "medium": $.PropertyDesc<$Medium, $.Cardinality.One, false, false, false, false>;
  "partnership": $.LinkDesc<_default.$Partnership, $.Cardinality.One, {}, false, false,  true, false>;
}>;
type $PartnershipProducingMedium = $.ObjectType<"Product::PartnershipProducingMedium", $PartnershipProducingMediumλShape, null, [
  ..._Engagement.$Child['__exclusives__'],
], "Product::PartnershipProducingMedium">;
const $PartnershipProducingMedium = $.makeType<$PartnershipProducingMedium>(_.spec, "1c785f8a-0670-11f0-88f6-2beeb6706f97", _.syntax.literal);

const PartnershipProducingMedium: $.$expr_PathNode<$.TypeSet<$PartnershipProducingMedium, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PartnershipProducingMedium, $.Cardinality.Many), null);



export { Medium, Methodology, ProgressMeasurement, Purpose, Step, $PartnershipProducingMedium, PartnershipProducingMedium };

type __defaultExports = {
  "Medium": typeof Medium;
  "Methodology": typeof Methodology;
  "ProgressMeasurement": typeof ProgressMeasurement;
  "Purpose": typeof Purpose;
  "Step": typeof Step;
  "PartnershipProducingMedium": typeof PartnershipProducingMedium
};
const __defaultExports: __defaultExports = {
  "Medium": Medium,
  "Methodology": Methodology,
  "ProgressMeasurement": ProgressMeasurement,
  "Purpose": Purpose,
  "Step": Step,
  "PartnershipProducingMedium": PartnershipProducingMedium
};
export default __defaultExports;
