// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import _module__ProductProgress from "./ProgressReport/ProductProgress";
import _module__Media from "./ProgressReport/Media";
import type * as _Engagement from "./Engagement";
import type * as _default from "./default";
import type * as _Prompt from "./Prompt";
import type * as _ProgressReportMedia from "./ProgressReport/Media";
import type * as _std from "./std";
export type $Status = {
  "NotStarted": $.$expr_Literal<$Status>;
  "InProgress": $.$expr_Literal<$Status>;
  "PendingTranslation": $.$expr_Literal<$Status>;
  "InReview": $.$expr_Literal<$Status>;
  "Approved": $.$expr_Literal<$Status>;
  "Published": $.$expr_Literal<$Status>;
} & $.EnumType<"ProgressReport::Status", ["NotStarted", "InProgress", "PendingTranslation", "InReview", "Approved", "Published"]>;
const Status: $Status = $.makeType<$Status>(_.spec, "1d3d0dc6-0670-11f0-829e-4f9648f840c6", _.syntax.literal);

export type $ChildλShape = $.typeutil.flatten<_Engagement.$ChildλShape & {
  "report": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  true, false>;
}>;
type $Child = $.ObjectType<"ProgressReport::Child", $ChildλShape, null, [
  ..._Engagement.$Child['__exclusives__'],
], "ProgressReport::CommunityStory" | "ProgressReport::Highlight" | "ProgressReport::Media" | "ProgressReport::TeamNews" | "ProgressReport::VarianceExplanation">;
const $Child = $.makeType<$Child>(_.spec, "1c9a075c-0670-11f0-8739-bd6c9b5d83d1", _.syntax.literal);

const Child: $.$expr_PathNode<$.TypeSet<$Child, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Child, $.Cardinality.Many), null);



export type $CommunityStoryλShape = $.typeutil.flatten<Omit<$ChildλShape, "container"> & Omit<_Prompt.$PromptVariantResponseλShape, "container"> & {
  "container": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $CommunityStory = $.ObjectType<"ProgressReport::CommunityStory", $CommunityStoryλShape, null, [
  ...$Child['__exclusives__'],
  ..._Prompt.$PromptVariantResponse['__exclusives__'],
], "ProgressReport::CommunityStory">;
const $CommunityStory = $.makeType<$CommunityStory>(_.spec, "1cbc7ea4-0670-11f0-bad5-7bca7c14a2a5", _.syntax.literal);

const CommunityStory: $.$expr_PathNode<$.TypeSet<$CommunityStory, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($CommunityStory, $.Cardinality.Many), null);



export type $HighlightλShape = $.typeutil.flatten<Omit<$ChildλShape, "container"> & Omit<_Prompt.$PromptVariantResponseλShape, "container"> & {
  "container": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Highlight = $.ObjectType<"ProgressReport::Highlight", $HighlightλShape, null, [
  ...$Child['__exclusives__'],
  ..._Prompt.$PromptVariantResponse['__exclusives__'],
], "ProgressReport::Highlight">;
const $Highlight = $.makeType<$Highlight>(_.spec, "1ccc5ad6-0670-11f0-a8ac-9f45c13254d8", _.syntax.literal);

const Highlight: $.$expr_PathNode<$.TypeSet<$Highlight, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Highlight, $.Cardinality.Many), null);

export type $MediaλShape = $.typeutil.flatten<$ChildλShape & {
  "variantGroup": $.LinkDesc<_ProgressReportMedia.$VariantGroup, $.Cardinality.One, {}, false, false,  false, false>;
  "variant": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "file": $.LinkDesc<_default.$File, $.Cardinality.One, {}, false, false,  false, false>;
  "media": $.LinkDesc<_default.$Media, $.Cardinality.One, {}, false, true,  false, false>;
  "category": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $Media = $.ObjectType<"ProgressReport::Media", $MediaλShape, null, [
  ...$Child['__exclusives__'],
  {variantGroup: {__element__: _ProgressReportMedia.$VariantGroup, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },variant: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "ProgressReport::Media">;
const $Media = $.makeType<$Media>(_.spec, "1cdea074-0670-11f0-9723-b9d4a567b0dd", _.syntax.literal);

const Media: $.$expr_PathNode<$.TypeSet<$Media, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Media, $.Cardinality.Many), null);

export type $TeamNewsλShape = $.typeutil.flatten<$ChildλShape & _Prompt.$PromptVariantResponseλShape & {
  "container": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $TeamNews = $.ObjectType<"ProgressReport::TeamNews", $TeamNewsλShape, null, [
  ...$Child['__exclusives__'],
  ..._Prompt.$PromptVariantResponse['__exclusives__'],
], "ProgressReport::TeamNews">;
const $TeamNews = $.makeType<$TeamNews>(_.spec, "1d1caf86-0670-11f0-b3d7-8fc7efc994bf", _.syntax.literal);

const TeamNews: $.$expr_PathNode<$.TypeSet<$TeamNews, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($TeamNews, $.Cardinality.Many), null);

export type $VarianceExplanationλShape = $.typeutil.flatten<Omit<$ChildλShape, "report"> & {
  "comments": $.PropertyDesc<_default.$RichText, $.Cardinality.AtMostOne, false, false, false, false>;
  "reasons": $.PropertyDesc<_std.$str, $.Cardinality.Many, false, false, false, false>;
  "report": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, true, false,  true, false>;
  "<varianceExplanation[is ProgressReport]": $.LinkDesc<_default.$ProgressReport, $.Cardinality.Many, {}, false, false,  false, false>;
  "<varianceExplanation": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $VarianceExplanation = $.ObjectType<"ProgressReport::VarianceExplanation", $VarianceExplanationλShape, null, [
  ...$Child['__exclusives__'],
  {report: {__element__: _default.$ProgressReport, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "ProgressReport::VarianceExplanation">;
const $VarianceExplanation = $.makeType<$VarianceExplanation>(_.spec, "1d2d4b8e-0670-11f0-85d7-3bb759bb1db8", _.syntax.literal);

const VarianceExplanation: $.$expr_PathNode<$.TypeSet<$VarianceExplanation, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($VarianceExplanation, $.Cardinality.Many), null);

export type $WorkflowEventλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "report": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  true, false>;
  "at": $.PropertyDesc<_std.$datetime, $.Cardinality.One, false, false, true, true>;
  "status": $.PropertyDesc<$Status, $.Cardinality.One, false, false, true, false>;
  "who": $.LinkDesc<_default.$User, $.Cardinality.One, {}, false, false,  true, true>;
  "notes": $.PropertyDesc<_default.$RichText, $.Cardinality.AtMostOne, false, false, true, false>;
  "transitionId": $.PropertyDesc<_default.$nanoid, $.Cardinality.AtMostOne, false, false, true, false>;
  "<workflowEvents[is ProgressReport]": $.LinkDesc<_default.$ProgressReport, $.Cardinality.Many, {}, false, false,  false, false>;
  "<latestEvent[is ProgressReport]": $.LinkDesc<_default.$ProgressReport, $.Cardinality.Many, {}, false, false,  false, false>;
  "<latestEvent": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
  "<workflowEvents": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $WorkflowEvent = $.ObjectType<"ProgressReport::WorkflowEvent", $WorkflowEventλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "ProgressReport::WorkflowEvent">;
const $WorkflowEvent = $.makeType<$WorkflowEvent>(_.spec, "1d6dd24e-0670-11f0-a3ae-3d19c96e305e", _.syntax.literal);

const WorkflowEvent: $.$expr_PathNode<$.TypeSet<$WorkflowEvent, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($WorkflowEvent, $.Cardinality.Many), null);



export { Status, $Child, Child, $CommunityStory, CommunityStory, $Highlight, Highlight, $Media, Media, $TeamNews, TeamNews, $VarianceExplanation, VarianceExplanation, $WorkflowEvent, WorkflowEvent };

type __defaultExports = {
  "Status": typeof Status;
  "Child": typeof Child;
  "CommunityStory": typeof CommunityStory;
  "Highlight": typeof Highlight;
  "Media": typeof _module__Media & typeof Media;
  "TeamNews": typeof TeamNews;
  "VarianceExplanation": typeof VarianceExplanation;
  "WorkflowEvent": typeof WorkflowEvent;
  "ProductProgress": typeof _module__ProductProgress
};
const __defaultExports: __defaultExports = {
  "Status": Status,
  "Child": Child,
  "CommunityStory": CommunityStory,
  "Highlight": Highlight,
  "Media": Object.freeze({ ..._module__Media, ...Media }),
  "TeamNews": TeamNews,
  "VarianceExplanation": VarianceExplanation,
  "WorkflowEvent": WorkflowEvent,
  "ProductProgress": _module__ProductProgress
};
export default __defaultExports;
