// GENERATED by @gel/generate v0.6.2

import * as $ from "../reflection";
import * as _ from "../imports";
import type * as _default from "./default";
import type * as _Mixin from "./Mixin";
import type * as _std from "./std";
import type * as _ProgressReport from "./ProgressReport";
export type $PromptVariantResponseλShape = $.typeutil.flatten<_default.$ResourceλShape & _Mixin.$EmbeddedλShape & {
  "promptId": $.PropertyDesc<_default.$nanoid, $.Cardinality.AtMostOne, false, false, false, false>;
  "responses": $.LinkDesc<$VariantResponse, $.Cardinality.Many, {}, false, true,  false, false>;
  "<pvr[is Prompt::VariantResponse]": $.LinkDesc<$VariantResponse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<pvr": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $PromptVariantResponse = $.ObjectType<"Prompt::PromptVariantResponse", $PromptVariantResponseλShape, null, [
  ..._default.$Resource['__exclusives__'],
  ..._Mixin.$Embedded['__exclusives__'],
], "ProgressReport::CommunityStory" | "ProgressReport::Highlight" | "ProgressReport::TeamNews">;
const $PromptVariantResponse = $.makeType<$PromptVariantResponse>(_.spec, "48316ae8-01a9-11f0-8b58-27bd65cb8916", _.syntax.literal);

const PromptVariantResponse: $.$expr_PathNode<$.TypeSet<$PromptVariantResponse, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($PromptVariantResponse, $.Cardinality.Many), null);

export type $VariantResponseλShape = $.typeutil.flatten<_Mixin.$AuditedλShape & {
  "pvr": $.LinkDesc<$PromptVariantResponse, $.Cardinality.One, {}, false, false,  false, false>;
  "variant": $.PropertyDesc<_std.$str, $.Cardinality.One, false, false, false, false>;
  "response": $.PropertyDesc<_default.$RichText, $.Cardinality.AtMostOne, false, false, false, false>;
  "<responses[is Prompt::PromptVariantResponse]": $.LinkDesc<$PromptVariantResponse, $.Cardinality.Many, {}, false, false,  false, false>;
  "<responses[is ProgressReport::TeamNews]": $.LinkDesc<_ProgressReport.$TeamNews, $.Cardinality.Many, {}, false, false,  false, false>;
  "<responses[is ProgressReport::Highlight]": $.LinkDesc<_ProgressReport.$Highlight, $.Cardinality.Many, {}, false, false,  false, false>;
  "<responses[is ProgressReport::CommunityStory]": $.LinkDesc<_ProgressReport.$CommunityStory, $.Cardinality.Many, {}, false, false,  false, false>;
  "<responses": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $VariantResponse = $.ObjectType<"Prompt::VariantResponse", $VariantResponseλShape, null, [
  ..._Mixin.$Audited['__exclusives__'],
  {pvr: {__element__: $PromptVariantResponse, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },variant: {__element__: _std.$str, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "Prompt::VariantResponse">;
const $VariantResponse = $.makeType<$VariantResponse>(_.spec, "49050d58-01a9-11f0-a21b-3b76b83feae6", _.syntax.literal);

const VariantResponse: $.$expr_PathNode<$.TypeSet<$VariantResponse, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($VariantResponse, $.Cardinality.Many), null);



export { $PromptVariantResponse, PromptVariantResponse, $VariantResponse, VariantResponse };

type __defaultExports = {
  "PromptVariantResponse": typeof PromptVariantResponse;
  "VariantResponse": typeof VariantResponse
};
const __defaultExports: __defaultExports = {
  "PromptVariantResponse": PromptVariantResponse,
  "VariantResponse": VariantResponse
};
export default __defaultExports;
