import { Book } from '@seedcompany/scripture';
import { BookDifficulty } from './dto';

export const difficultyFactorOfBook = (book: Book): number =>
  factorMap[difficultyOfBook(book)];

export const difficultyOfBook = (book: Book) => difficultyMap[book.name];

const factorMap: Record<BookDifficulty, number> = {
  Easy: 0.8,
  Normal: 1,
  Hard: 1.25,
  Hardest: 1.5625,
};

const difficultyMap: Record<string, `${BookDifficulty}`> = {
  Genesis: 'Normal',
  Exodus: 'Normal',
  Leviticus: 'Hard',
  Numbers: 'Normal',
  Deuteronomy: 'Normal',
  Joshua: 'Easy',
  Judges: 'Easy',
  Ruth: 'Easy',
  '1 Samuel': 'Easy',
  '2 Samuel': 'Easy',
  '1 Kings': 'Easy',
  '2 Kings': 'Easy',
  '1 Chronicles': 'Easy',
  '2 Chronicles': 'Easy',
  Ezra: 'Normal',
  Nehemiah: 'Normal',
  Esther: 'Easy',
  Job: 'Hardest',
  Psalm: 'Hard',
  Proverbs: 'Hard',
  Ecclesiastes: 'Hard',
  'Song of Solomon': 'Hard',
  Isaiah: 'Hardest',
  Jeremiah: 'Hardest',
  Lamentations: 'Hardest',
  Ezekiel: 'Hardest',
  Daniel: 'Hard',
  Hosea: 'Hardest',
  Joel: 'Hardest',
  Amos: 'Hardest',
  Obadiah: 'Hardest',
  Jonah: 'Easy',
  Micah: 'Hardest',
  Nahum: 'Hardest',
  Habakkuk: 'Hardest',
  Zephaniah: 'Hardest',
  Haggai: 'Hard',
  Zechariah: 'Hardest',
  Malachi: 'Hard',
  Matthew: 'Normal',
  Mark: 'Normal',
  Luke: 'Normal',
  John: 'Hard',
  Acts: 'Normal',
  Romans: 'Hardest',
  '1 Corinthians': 'Hard',
  '2 Corinthians': 'Hard',
  Galatians: 'Hardest',
  Ephesians: 'Hardest',
  Philippians: 'Hardest',
  Colossians: 'Hardest',
  '1 Thessalonians': 'Hard',
  '2 Thessalonians': 'Hard',
  '1 Timothy': 'Normal',
  '2 Timothy': 'Normal',
  Titus: 'Normal',
  Philemon: 'Normal',
  Hebrews: 'Hardest',
  James: 'Normal',
  '1 Peter': 'Hard',
  '2 Peter': 'Hard',
  '1 John': 'Hard',
  '2 John': 'Normal',
  '3 John': 'Normal',
  Jude: 'Normal',
  Revelation: 'Normal',
};
