export enum POWERS {
  CREATE_USER = 'CREATE_USER',
  DELETE_USER = 'DELETE_USER',
  CREATE_PROJECT = 'CREATE_PROJECT',
  DELETE_PROJECT = 'DELETE_PROJECT',
  CREATE_WORKFLOW = 'CREATE_WORKFLOW',
  DELETE_WORKFLOW = 'DELETE_WORKFLOW',
  CREATE_SECURITY_GROUP = 'CREATE_SECURITY_GROUP',
  DELETE_SECURITY_GROUP = 'DELETE_SECURITY_GROUP',
  CREATE_ORGANIZATION = 'CREATE_ORGANIZATION',
  DELETE_ORGANIZATION = 'DELETE_ORGANIZATION',
}
