export enum BibleBook {
  Genesis = 'gen',
  Exodus = 'exo',
  Leviticus = 'lev',
  Numbers = 'num',
  Deuteronomy = 'deu',
  Joshua = 'jos',
  Judges = 'jdg',
  Ruth = 'rut',
  FirstSamuel = '1sa',
  SecondSamuel = '2sa',
  FirstKings = '1ki',
  SecondKings = '2ki',
  FirstChronicles = '1ch',
  SecondChronicles = '2ch',
  Ezra = 'ezr',
  Nehemiah = 'neh',
  Esther = 'est',
  Job = 'job',
  Psalms = 'psa',
  Proverbs = 'pro',
  Ecclesiastes = 'ecc',
  SongOfSolomon = 'sng',
  Isaiah = 'isa',
  Jeremiah = 'jer',
  Lamentations = 'lam',
  Ezekiel = 'ezk',
  Daniel = 'dan',
  Hosea = 'hos',
  Joel = 'jol',
  Amos = 'amo',
  Obadiah = 'oba',
  Jonah = 'jon',
  Micah = 'mic',
  Nahum = 'nam',
  Habakkuk = 'hab',
  Zephaniah = 'zep',
  Haggai = 'hag',
  Zechariah = 'zec',
  Malachi = 'mal',

  Matthew = 'mat',
  Mark = 'mrk',
  Luke = 'luk',
  John = 'jhn',
  Acts = 'act',
  Romans = 'rom',
  FirstCorinthians = '1co',
  SecondCorinthians = '2co',
  Galatians = 'gal',
  Ephesians = 'eph',
  Philippians = 'php',
  Colossians = 'col',
  FirstThessalonians = '1th',
  SecondThessalonians = '2th',
  FirstTimothy = '1ti',
  SecondTimothy = '2ti',
  Titus = 'tit',
  Philemon = 'phm',
  Hebrews = 'heb',
  James = 'jas',
  FirstPeter = '1pe',
  SecondPeter = '2pe',
  FirstJohn = '1jn',
  SecondJohn = '2jn',
  ThirdJohn = '3jn',
  Jude = 'jud',
  Revelation = 'rev',
}

export const Bible = {
  Full: Object.values(BibleBook) as BibleBook[],
  OldTestament: [
    BibleBook.Genesis,
    BibleBook.Exodus,
    BibleBook.Leviticus,
    BibleBook.Numbers,
    BibleBook.Deuteronomy,
    BibleBook.Joshua,
    BibleBook.Judges,
    BibleBook.Ruth,
    BibleBook.FirstSamuel,
    BibleBook.SecondSamuel,
    BibleBook.FirstKings,
    BibleBook.SecondKings,
    BibleBook.FirstChronicles,
    BibleBook.SecondChronicles,
    BibleBook.Ezra,
    BibleBook.Nehemiah,
    BibleBook.Esther,
    BibleBook.Job,
    BibleBook.Psalms,
    BibleBook.Proverbs,
    BibleBook.Ecclesiastes,
    BibleBook.SongOfSolomon,
    BibleBook.Isaiah,
    BibleBook.Jeremiah,
    BibleBook.Lamentations,
    BibleBook.Ezekiel,
    BibleBook.Daniel,
    BibleBook.Hosea,
    BibleBook.Joel,
    BibleBook.Amos,
    BibleBook.Obadiah,
    BibleBook.Jonah,
    BibleBook.Micah,
    BibleBook.Nahum,
    BibleBook.Habakkuk,
    BibleBook.Zephaniah,
    BibleBook.Haggai,
    BibleBook.Zechariah,
    BibleBook.Malachi,
  ],
  NewTestament: [
    BibleBook.Matthew,
    BibleBook.Mark,
    BibleBook.Luke,
    BibleBook.John,
    BibleBook.Acts,
    BibleBook.Romans,
    BibleBook.FirstCorinthians,
    BibleBook.SecondCorinthians,
    BibleBook.Galatians,
    BibleBook.Ephesians,
    BibleBook.Philippians,
    BibleBook.Colossians,
    BibleBook.FirstThessalonians,
    BibleBook.SecondThessalonians,
    BibleBook.FirstTimothy,
    BibleBook.SecondTimothy,
    BibleBook.Titus,
    BibleBook.Philemon,
    BibleBook.Hebrews,
    BibleBook.James,
    BibleBook.FirstPeter,
    BibleBook.SecondPeter,
    BibleBook.FirstJohn,
    BibleBook.SecondJohn,
    BibleBook.ThirdJohn,
    BibleBook.Jude,
    BibleBook.Revelation,
  ],
  Gospels: [BibleBook.Matthew, BibleBook.Mark, BibleBook.Luke, BibleBook.John],
};
