name: Setup EdgeDB
description: 'Setup EdgeDB server, migrate schema, generate TS files'
runs:
  using: composite
  steps:
    - name: Setup EdgeDB
      uses: edgedb/setup-edgedb@v1

    - run: edgedb configure set session_idle_transaction_timeout 5min
      shell: bash

    - name: Generate EdgeDB TS files
      shell: bash
      run: yarn edgedb:gen
