name: Setup EdgeDB
description: 'Setup EdgeDB server, migrate schema, generate TS files'

runs:
  using: composite
  steps:
    - name: Setup EdgeDB
      uses: edgedb/setup-edgedb@v1
      with:
        cli-version: nightly
        server-dsn: none

    - name: Branch & Migrate
      shell: bash
      run: |
        edgedb branch create github_$PR_NUMBER_$GITHUB_RUN_ID_$GITHUB_RUN_ATTEMPT_$GITHUB_JOB
        edgedb branch switch github_$PR_NUMBER_$GITHUB_RUN_ID_$GITHUB_RUN_ATTEMPT_$GITHUB_JOB
        edgedb migrate
      env:
        PR_NUMBER: ${{ github.event.number }}

    - name: Generate EdgeDB TS files
      shell: bash
      run: yarn edgedb:gen
