name: Setup EdgeDB
description: 'Setup EdgeDB server, migrate schema, generate TS files'

env:
  BRANCH: github_${{ github.event.number }}_${{ env.GITHUB_RUN_ID }}_${{ env.GITHUB_RUN_ATTEMPT }}_${{ env.GITHUB_JOB }}

runs:
  using: composite
  steps:
    - name: Setup EdgeDB
      uses: edgedb/setup-edgedb@v1
      with:
        cli-version: nightly
        server-dsn: none

    - name: Branch & Migrate
      shell: bash
      run: |
        echo "Creating branch $BRANCH"
        edgedb branch create $BRANCH
        echo "Switching to branch $BRANCH"
        edgedb branch switch $BRANCH
        echo "Applying new migrations to branch $BRANCH"
        edgedb migrate

    - name: Generate EdgeDB TS files
      shell: bash
      run: yarn edgedb:gen
