import { registerEnumType } from '@nestjs/graphql';

export enum BibleBook {
  Genesis = 'Genesis',
  Exodus = 'Exodus',
  Leviticus = 'Leviticus',
  Numbers = 'Numbers',
  Deuteronomy = 'Deuteronomy',
  Joshua = 'Joshua',
  Judges = 'Judges',
  Ruth = 'Ruth',
  FirstSamuel = 'FirstSamuel',
  SecondSamuel = 'SecondSamuel',
  FirstKings = 'FirstKings',
  SecondKings = 'SecondKings',
  FirstChronicles = 'FirstChronicles',
  SecondChronicles = 'SecondChronicles',
  Ezra = 'Ezra',
  Nehemiah = 'Nehemiah',
  Esther = 'Esther',
  Job = 'Job',
  Psalms = 'Psalms',
  Proverbs = 'Proverbs',
  Ecclesiastes = 'Ecclesiastes',
  SongOfSolomon = 'SongOfSolomon',
  Isaiah = 'Isaiah',
  Jeremiah = 'Jeremiah',
  Lamentations = 'Lamentations',
  Ezekiel = 'Ezekiel',
  Daniel = 'Daniel',
  Hosea = 'Hosea',
  Joel = 'Joel',
  Amos = 'Amos',
  Obadiah = 'Obadiah',
  Jonah = 'Jonah',
  Micah = 'Micah',
  Nahum = 'Nahum',
  Habakkuk = 'Habakkuk',
  Zephaniah = 'Zephaniah',
  Haggai = 'Haggai',
  Zechariah = 'Zechariah',
  Malachi = 'Malachi',

  Matthew = 'Matthew',
  Mark = 'Mark',
  Luke = 'Luke',
  John = 'John',
  Acts = 'Acts',
  Romans = 'Romans',
  FirstCorinthians = 'FirstCorinthians',
  SecondCorinthians = 'SecondCorinthians',
  Galatians = 'Galatians',
  Ephesians = 'Ephesians',
  Philippians = 'Philippians',
  Colossians = 'Colossians',
  FirstThessalonians = 'FirstThessalonians',
  SecondThessalonians = 'SecondThessalonians',
  FirstTimothy = 'FirstTimothy',
  SecondTimothy = 'SecondTimothy',
  Titus = 'Titus',
  Philemon = 'Philemon',
  Hebrews = 'Hebrews',
  James = 'James',
  FirstPeter = 'FirstPeter',
  SecondPeter = 'SecondPeter',
  FirstJohn = 'FirstJohn',
  SecondJohn = 'SecondJohn',
  ThirdJohn = 'ThirdJohn',
  Jude = 'Jude',
  Revelation = 'Revelation',
}

registerEnumType(BibleBook, {
  name: 'BibleBook',
});
