// GENERATED by @gel/generate v0.6.2

import * as $ from "../../reflection";
import * as _ from "../../imports";
import type * as _std from "../std";
import type * as _ProgressReport from "../ProgressReport";
export type $VariantGroupλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "<variantGroup[is ProgressReport::Media]": $.LinkDesc<_ProgressReport.$Media, $.Cardinality.Many, {}, false, false,  false, false>;
  "<variantGroup": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $VariantGroup = $.ObjectType<"ProgressReport::Media::VariantGroup", $VariantGroupλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
], "ProgressReport::Media::VariantGroup">;
const $VariantGroup = $.makeType<$VariantGroup>(_.spec, "1cdc76dc-0670-11f0-b0b9-1b1a3b716348", _.syntax.literal);

const VariantGroup: $.$expr_PathNode<$.TypeSet<$VariantGroup, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($VariantGroup, $.Cardinality.Many), null);



export { $VariantGroup, VariantGroup };

type __defaultExports = {
  "VariantGroup": typeof VariantGroup
};
const __defaultExports: __defaultExports = {
  "VariantGroup": VariantGroup
};
export default __defaultExports;
