// GENERATED by @gel/generate v0.6.2

import * as $ from "../../reflection";
import * as _ from "../../imports";
import type * as _Mixin from "../Mixin";
import type * as _Project from "../Project";
import type * as _default from "../default";
import type * as _Product from "../Product";
import type * as _std from "../std";
export type $Period = {
  "ReportPeriod": $.$expr_Literal<$Period>;
  "FiscalYearSoFar": $.$expr_Literal<$Period>;
  "Cumulative": $.$expr_Literal<$Period>;
} & $.EnumType<"ProgressReport::ProductProgress::Period", ["ReportPeriod", "FiscalYearSoFar", "Cumulative"]>;
const Period: $Period = $.makeType<$Period>(_.spec, "49526972-01a9-11f0-bd67-0f8613427013", _.syntax.literal);

export type $Variant = {
  "Official": $.$expr_Literal<$Variant>;
  "Partner": $.$expr_Literal<$Variant>;
} & $.EnumType<"ProgressReport::ProductProgress::Variant", ["Official", "Partner"]>;
const Variant: $Variant = $.makeType<$Variant>(_.spec, "492dc360-01a9-11f0-8133-251ff6fd659d", _.syntax.literal);

export type $StepλShape = $.typeutil.flatten<_Mixin.$TimestampedλShape & _Project.$ContextAwareλShape & {
  "report": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  false, false>;
  "step": $.PropertyDesc<_Product.$Step, $.Cardinality.One, false, false, false, false>;
  "variant": $.PropertyDesc<$Variant, $.Cardinality.One, false, false, false, false>;
  "completed": $.PropertyDesc<_std.$float32, $.Cardinality.AtMostOne, false, false, false, false>;
  "product": $.LinkDesc<_default.$Product, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $Step = $.ObjectType<"ProgressReport::ProductProgress::Step", $StepλShape, null, [
  ..._Mixin.$Timestamped['__exclusives__'],
  ..._Project.$ContextAware['__exclusives__'],
  {report: {__element__: _default.$ProgressReport, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },product: {__element__: _default.$Product, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },variant: {__element__: $Variant, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },step: {__element__: _Product.$Step, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "ProgressReport::ProductProgress::Step">;
const $Step = $.makeType<$Step>(_.spec, "492ddd82-01a9-11f0-80f1-2b1a6246d5f6", _.syntax.literal);

const Step: $.$expr_PathNode<$.TypeSet<$Step, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Step, $.Cardinality.Many), null);

export type $SummaryλShape = $.typeutil.flatten<_std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588λShape & {
  "report": $.LinkDesc<_default.$ProgressReport, $.Cardinality.One, {}, false, false,  false, false>;
  "period": $.PropertyDesc<$Period, $.Cardinality.One, false, false, false, false>;
  "actual": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
  "planned": $.PropertyDesc<_std.$float32, $.Cardinality.One, false, false, false, false>;
}>;
type $Summary = $.ObjectType<"ProgressReport::ProductProgress::Summary", $SummaryλShape, null, [
  ..._std.$Object_8ce8c71ee4fa5f73840c22d7eaa58588['__exclusives__'],
  {report: {__element__: _default.$ProgressReport, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },period: {__element__: $Period, __cardinality__: $.Cardinality.One | $.Cardinality.AtMostOne },},
], "ProgressReport::ProductProgress::Summary">;
const $Summary = $.makeType<$Summary>(_.spec, "49527cdc-01a9-11f0-8022-3fba4c1d1294", _.syntax.literal);

const Summary: $.$expr_PathNode<$.TypeSet<$Summary, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($Summary, $.Cardinality.Many), null);



export { Period, Variant, $Step, Step, $Summary, Summary };

type __defaultExports = {
  "Period": typeof Period;
  "Variant": typeof Variant;
  "Step": typeof Step;
  "Summary": typeof Summary
};
const __defaultExports: __defaultExports = {
  "Period": Period,
  "Variant": Variant,
  "Step": Step,
  "Summary": Summary
};
export default __defaultExports;
