name: CI
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Install dependencies
        run: yarn install --immutable && yarn dedupe --check
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Check TypeScript
        run: yarn type-check

      - name: Lint
        run: yarn eslint --ext .ts,.tsx --max-warnings 0 .

  gql-breaking-changes:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: base
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: actions/cache@v1
        id: yarn-cache-base
        with:
          path: base/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('base/yarn.lock') }}-${{ hashFiles('base/.yarnrc.yml') }}
      - run: yarn install --immutable && yarn dedupe --check
        working-directory: base
        if: steps.yarn-cache-base.outputs.cache-hit != 'true'
      - run: yarn start -- --gen-schema
        working-directory: base

      - uses: actions/checkout@v2
        with:
          path: head
      - uses: actions/cache@v1
        id: yarn-cache-head
        with:
          path: head/node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('head/yarn.lock') }}-${{ hashFiles('head/.yarnrc.yml') }}
      - run: yarn install --immutable && yarn dedupe --check
        if: steps.yarn-cache-head.outputs.cache-hit != 'true'
        working-directory: head
      - run: yarn start -- --gen-schema
        working-directory: head

      - name: Schema Diff
        run: |
          yarn dlx -q graphql-schema-diff \
            --use-colors --fail-on-breaking-changes --sort-schema \
            ../base/schema.graphql ./schema.graphql
        working-directory: head

  test:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: ghcr.io/seedcompany/cord-procedures
        ports:
          - 7474:7474
          - 7687:7687
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: neo4j/neo4j-password
          NEO4JLABS_PLUGINS: '["apoc"]'

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.12

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Install dependencies
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Tests
        run: node --expose-gc --no-compilation-cache ./node_modules/.bin/jest -i --config ./test/jest-e2e.json --runInBand --logHeapUsage
        env:
          NEO4J_URL: bolt://localhost:7687
          NEO4J_USERNAME: neo4j
          NEO4J_PASSWORD: neo4j-password
          NODE_OPTIONS: "--max_old_space_size=8192 --max-old-space-size=8192"

      - name: Upload Schema
        uses: actions/upload-artifact@v2
        with:
          name: schema.graphql
          path: schema.graphql
