name: CI
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:3.5-enterprise
        ports:
          - 7474:7474
          - 7687:7687
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: neo4j/neo4j-password

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Get yarn cache directory
        id: yarn_cache_dir
        run: |
          echo "::set-output name=dir::$(yarn config get cacheFolder)"
      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: ${{ steps.yarn_cache_dir.outputs['dir'] }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install

      - name: Check TypeScript
        run: yarn type-check

      - name: Lint
        run: yarn eslint --ext .ts,.tsx --max-warnings 0 .

      - name: Tests
        run: yarn test:e2e --runInBand
        env:
          NEO4J_URL: bolt://localhost:7687
          NEO4J_USERNAME: neo4j
          NEO4J_PASSWORD: neo4j-password
