name: CI
on:
  pull_request:
  push:
    branches:
      - master
  workflow_run:
    workflows:
      - Dependabot
    types:
      - completed

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Install dependencies
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Check TypeScript
        run: yarn type-check

      - name: Lint
        run: yarn eslint --ext .ts,.tsx --max-warnings 0 .

  test:
    runs-on: ubuntu-latest

    services:
      neo4j:
        image: neo4j:3.5-enterprise
        ports:
          - 7474:7474
          - 7687:7687
        env:
          NEO4J_ACCEPT_LICENSE_AGREEMENT: yes
          NEO4J_AUTH: neo4j/neo4j-password

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Install dependencies
        run: yarn install
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Tests
        run: yarn test:e2e --runInBand
        env:
          NEO4J_URL: bolt://localhost:7687
          NEO4J_USERNAME: neo4j
          NEO4J_PASSWORD: neo4j-password
