name: EdgeDB
on:
  pull_request:

env:
  EDGEDB_INSTANCE: ${{ secrets.EDGEDB_INSTANCE }}
  EDGEDB_SECRET_KEY: ${{ secrets.EDGEDB_SECRET_KEY }}

jobs:
  Clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node Setup & Yarn Install
        uses: ./.github/actions/setup

      - name: EdgeDB Setup
        uses: ./.github/actions/edgedb-setup

      - name: Inject Access Policies
        run: yarn console edgedb ap inject

      - name: Schema Migrations In Sync
        run: edgedb migration status
        if: github.event.pull_request.draft == false

      - name: Validate seed scripts are error free
        run: yarn edgedb:seed
        shell: bash

      - name: EdgeDB Teardown
        uses: ./.github/actions/edgedb-teardown
        if: always()
