name: EdgeDB
on:
  pull_request:

jobs:
  Clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Node Setup & Yarn Install
        uses: ./.github/actions/setup

      - uses: edgedb/setup-edgedb@v1

      - name: Schema Migrations In Sync
        run: edgedb migration status

      - name: Validate seed scripts are error free
        run: yarn edgedb:seed
        shell: bash
