name: Lint
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Yarn cache
        uses: actions/cache@v3
        with:
          path: |
            .yarn/cache
            node_modules
          key: yarn-cache-${{ hashFiles('yarn.lock', '.yarnrc.yml') }}
          restore-keys: yarn-cache-

      - name: Install dependencies
        run: yarn install --immutable && yarn dedupe --check

      - name: Check TypeScript
        run: yarn type-check

      - name: Generate GQL Schema
        run: yarn start -- --gen-schema
      - name: Upload GQL Schema
        uses: actions/upload-artifact@v3
        with:
          name: schema.graphql
          path: schema.graphql

      - name: Lint
        run: yarn eslint --ext .ts,.tsx --max-warnings 0 .
