name: Lint
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Node Setup & Yarn Install
        uses: ./.github/actions/setup

      - name: EdgeDB Setup
        uses: ./.github/actions/edgedb-setup
        with:
          dsn: ${{ secrets.EDGEDB_DSN }}

      - name: Check for no duplicate dependencies
        run: yarn dedupe --check

      - name: Check TypeScript
        run: yarn type-check

      - name: Generate GQL Schema
        run: yarn start -- --gen-schema
      - name: Upload GQL Schema
        uses: actions/upload-artifact@v4
        with:
          name: schema.graphql
          path: schema.graphql

      - name: Lint
        run: yarn eslint --ext .ts,.tsx --max-warnings 0 .

      - name: EdgeDB Teardown
        uses: ./.github/actions/edgedb-teardown
        if: always()
