name: Lint
on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Yarn cache
        uses: actions/cache@v1
        id: yarn-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('yarn.lock') }}-${{ hashFiles('.yarnrc.yml') }}

      - name: Install dependencies
        run: yarn install --immutable && yarn dedupe --check
        if: steps.yarn-cache.outputs.cache-hit != 'true'

      - name: Check TypeScript
        run: yarn type-check

      - name: Generate GQL Schema
        run: yarn start -- --gen-schema
      - name: Upload GQL Schema
        uses: actions/upload-artifact@v2
        with:
          name: schema.graphql
          path: schema.graphql

      - name: Lint
        run: yarn eslint --ext .ts,.tsx --max-warnings 0 .
